target_file_path = "camera_sevivi.avi"

[[video]]
type = "imu"
path = "test_files/videos/imu_sync.mp4"
imu_path = "test_files/sensors/imu_synchronization/camera_imu.csv.gz"

[[sensor]]
type = "camera-imu-synced"
sensor_sync_column_selection = "ACCELERATION"
camera_imu_sync_column_selection = "ACCELERATION"
path = "test_files/sensors/imu_synchronization/LF.csv.gz"
