[[video]]
type = "raw"
path = "test_files/videos/joint_synchronization_walking.mp4"

[[sensor]]
type = "manually-synced"
path = "test_files/sensors/joint_synchronization_walking/LF.csv.gz"
name = "LF"
offset_seconds = -4
graph_groups = ["Acc", "Gyr"]


[[sensor]]
type = "manually-synced"
path = "test_files/sensors/joint_synchronization_walking/RF.csv.gz"
name = "RF"
offset_seconds = -4
graph_groups = ["Acc", "Gyr"]
