target_file_path = "app_sevivi.avi"

[[video]]
type = "videoImuApp"
path = "test_files/videos/imu_sync.mp4"
imu_path = "test_files/sensors/video_imu_capture_app/video_meta.pb3"

[[sensor]]
type = "camera-imu-synced"
sensor_sync_column_selection = "ACCELERATION"
camera_imu_sync_column_selection = "ACCELERATION"
path = "test_files/sensors/imu_synchronization/LF.csv.gz"
