# May be 'vertical' to put all sensor graphs below the video, or 'horizontal' to put the sensor graphs left and right of
# the center of the video
stacking_direction = "horizontal"
#
draw_ticks = false
add_magnitude = false
use_parallel_image_ingestion = true
plotting_method = "moving_vertical_line"
