show_peak_finding_plots = false
stacking_direction = "horizontal"
draw_ticks = false
add_magnitude = false
add_events = true
add_gyroscope = true
use_parallel_image_ingestion = true
plotting_method = "moving_vline"
