# this is an object so that we don't get problems merging multiple files configuring a single sensor
[[sensor]]
type = "manually-synced"
path = "test_files/data/imu1.csv.gz"
offset_seconds = 0.123

[[sensor]]
type = "manually-synced"
path = "test_files/data/imu2.csv.gz"
offset_seconds = 123.1
