[[sensor]]
type = "joint-synced"
# this is the sensor df column names; multiple -> magnitude; single -> glob pattern
sensor_sync_column_selection = ["AccX", "Accel Y", "ACC Z"]
# this is the camera column names; multiple -> magnitude; single -> glob pattern
camera_joint_sync_column_selection = ["AccX", "Accel Y", "ACC Z"]
path = "test_files/joint_imu.csv.gz"
